### ISSUE TITLE
Installation process doesn't seem to work

### ISSUE THREAD

**Issue by mwcz** [eguneys/generator-phaserjs#1]
Here are the commands I ran, copied and pasted from the README.

```
sudo npm install -g generator-phaserjs
```

(installed successfully)

```
mkdir my-new-project && cd $
yo phaserjs
```

That resulted in:

```
Error phaserjs 

You don't seem to have a generator with the name phaserjs installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.
```

**Comment by eguneys** [comment]
It should work now, try again please. (Note that you shouldn't have to use `sudo`)

**Comment by mwcz** [comment]
Perfect, thanks!

**Comment by eguneys** [comment]
@mwcz , However the build has been failed, I don't know why, let me know if you encounter further issues.

**Comment by mwcz** [comment]
I saw that, doesn't look too bad though.  With default options, I'm seeing the same thing as the test.  It looks like `app/scripts/prefabs/` didn't get created.  Also `app/scripts/states/teststate.js` doesn't get created.

When I get a chance to toy with it, I'll let you know if that causes any problems.

@eguneys++
